dependencies:
 - OpenZeppelin/openzeppelin-contracts@4.7.2
compiler:
 solc:
  remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.2'
dotenv: .env
wallets:
  from_keys: ${PRIVATE_KEYS}
paramers:
  funding_admins: ${FUNDING_ADMINS}
  aragon_agent: ${ARAGON_AGENT}
  deployer: ${DEPLOYER}
